const PAYMENT_URLS: [string, string][] = [
    // ── Major national banks ──────────────────────────────────────────────────
    ['chase',               'https://www.chase.com/digital/pages/card-payments/card-payments'],
    ['bank of america',     'https://secure.bankofamerica.com/myaccounts/signIn/signIn.go'],
    ['capital one',         'https://myaccounts.capitalone.com/accountSummary'],
    ['citi',                'https://online.citibank.com/US/JPS/pands/Payments.do'],
    ['discover',            'https://portal.discover.com/customersvcs/universalLogin/ac_main'],
    ['american express',    'https://www.americanexpress.com/en-us/payments/'],
    ['amex',                'https://www.americanexpress.com/en-us/payments/'],
    ['wells fargo',         'https://connect.secure.wellsfargo.com/auth/login/present'],
    ['us bank',             'https://onlinebanking.usbank.com/'],
    ['u.s. bank',           'https://onlinebanking.usbank.com/'],
    ['td bank',             'https://onlinebanking.tdbank.com/'],
    ['pnc',                 'https://www.pnc.com/en/personal-banking/banking/online-and-mobile-banking.html'],
    ['hsbc',                'https://www.us.hsbc.com/'],
    ['santander',           'https://www.santanderbank.com/'],
    ['m&t bank',            'https://www.mtb.com/'],
    ['huntington',          'https://www.huntington.com/'],
    ['comerica',            'https://www.comerica.com/'],
    ['first citizens',      'https://www.firstcitizens.com/'],
    ['valley national',     'https://www.valleynationalbank.com/'],
    ['pinnacle',            'https://www.pnfp.com/'],
    ['glacier bank',        'https://www.glacierbank.com/'],
    ['banner bank',         'https://www.bannerbank.com/'],
    ['frost bank',          'https://www.frostbank.com/'],
    ['arvest',              'https://www.arvest.com/'],
    ['independent bank',    'https://www.independentbank.com/'],
    ['first interstate',    'https://www.firstinterstatebank.com/'],
    ['heartland financial', 'https://www.htlf.com/'],
    ['columbia banking',    'https://www.columbiabankingsystem.com/'],
    ['seacoast bank',       'https://www.seacoastbank.com/'],
    ['pacific premier',     'https://www.ppbi.com/'],
    ['western alliance',    'https://www.westernalliancebancorporation.com/'],
    ['firstbank',           'https://www.efirstbank.com/'],

    // ── Credit unions ─────────────────────────────────────────────────────────
    ['navy federal',        'https://www.navyfederal.org/'],
    ['usaa',                'https://www.usaa.com/'],
    ['penfed',              'https://www.penfed.org/'],
    ['pentagon federal',    'https://www.penfed.org/'],
    ['alliant',             'https://www.alliantcreditunion.org/'],
    ['becu',                'https://www.becu.org/'],
    ['connexus',            'https://www.connexuscu.org/'],
    ['suncoast',            'https://www.suncoast.com/'],
    ['america first',       'https://www.americafirst.com/'],
    ['mountain america',    'https://www.macu.com/'],
    ['rbfcu',               'https://www.rbfcu.org/'],
    ['randolph-brooks',     'https://www.rbfcu.org/'],
    ['golden 1',            'https://www.golden1.com/'],
    ['vystar',              'https://www.vystarcu.org/'],
    ['schoolsfirst',        'https://www.schoolsfirstfcu.org/'],
    ['first tech',          'https://www.firsttech.com/'],
    ['desert financial',    'https://www.desertfinancial.com/'],
    ['dcu',                 'https://www.dcu.org/'],
    ['digital federal',     'https://www.dcu.org/'],
    ['wright-patt',         'https://www.wpcu.coop/'],
    ['tinker federal',      'https://www.tinker.org/'],
    ['langley federal',     'https://www.langleyfcu.org/'],
    ['redstone federal',    'https://www.redstonefcu.org/'],
    ['grow financial',      'https://www.growfinancial.org/'],
    ['truliant',            'https://www.truliant.org/'],
    ['members 1st',         'https://www.members1st.org/'],
    ['state employees',     'https://www.secu.org/'],

    // ── Regional / community banks ────────────────────────────────────────────
    ['citizens',            'https://www.citizensbank.com/'],
    ['truist',              'https://www.truist.com/'],
    ['regions',             'https://www.regions.com/'],
    ['fifth third',         'https://www.53.com/'],
    ['keycorp',             'https://www.key.com/'],
    ['key bank',            'https://www.key.com/'],
    ['suntrust',            'https://www.truist.com/'],
    ['bb&t',                'https://www.truist.com/'],
    ['bbt',                 'https://www.truist.com/'],
    ['nfcu',                'https://www.navyfederal.org/'],
    ['bmo',                 'https://www.bmoharrisbank.com/'],
    ['bmo harris',          'https://www.bmoharrisbank.com/'],

    // ── Auto lenders ──────────────────────────────────────────────────────────
    ['gm financial',        'https://www.gmfinancial.com/'],
    ['ford motor credit',   'https://www.fordcredit.com/'],
    ['ford credit',         'https://www.fordcredit.com/'],
    ['toyota financial',    'https://www.toyotafinancial.com/'],
    ['honda financial',     'https://www.hfs.honda.com/'],
    ['nissan motor',        'https://www.nissanfinance.com/'],
    ['hyundai motor',       'https://www.hmfusa.com/'],
    ['kia finance',         'https://www.kiafinancialservices.com/'],
    ['kia motors finance',  'https://www.kiafinancialservices.com/'],
    ['bmw financial',       'https://www.bmwfinancialservices.com/'],
    ['mercedes-benz',       'https://www.mbfs.com/'],
    ['volkswagen credit',   'https://www.vwcredit.com/'],
    ['audi financial',      'https://www.audifinancialservices.com/'],
    ['subaru motors',       'https://www.subarufinance.com/'],
    ['chrysler capital',    'https://www.chryslercapital.com/'],
    ['westlake financial',  'https://www.westlakefinancial.com/'],
    ['santander consumer',  'https://www.santanderconsumerusa.com/'],
    ['credit acceptance',   'https://www.creditacceptance.com/'],
    ['carvana',             'https://www.carvana.com/'],
    ['carmax auto',         'https://www.carmaxautofinance.com/'],

    // ── Student loan servicers ────────────────────────────────────────────────
    ['navient',             'https://www.navient.com/'],
    ['nelnet',              'https://www.nelnet.com/'],
    ['mohela',              'https://www.mohela.com/'],
    ['aidvantage',          'https://aidvantage.com/'],
    ['edfinancial',         'https://www.edfinancial.com/'],
    ['sallie mae',          'https://www.salliemae.com/'],
    ['college ave',         'https://www.collegeave.com/'],
    ['earnest',             'https://www.earnest.com/'],
    ['commonbond',          'https://commonbond.co/'],
    ['great lakes',         'https://www.mygreatlakes.org/'],
    ['osla',                'https://www.osla.org/'],

    // ── Mortgage servicers ────────────────────────────────────────────────────
    ['mr. cooper',          'https://www.mrcooper.com/'],
    ['mr cooper',           'https://www.mrcooper.com/'],
    ['nationstar',          'https://www.mrcooper.com/'],
    ['rocket mortgage',     'https://www.rocketmortgage.com/'],
    ['quicken loans',       'https://www.rocketmortgage.com/'],
    ['freedom mortgage',    'https://www.freedommortgage.com/'],
    ['pennymac',            'https://www.pennymac.com/'],
    ['loandepot',           'https://www.loandepot.com/'],
    ['loan depot',          'https://www.loandepot.com/'],
    ['newrez',              'https://www.newrez.com/'],
    ['shellpoint',          'https://www.shellpointmtg.com/'],
    ['caliber home',        'https://www.caliberhomeloans.com/'],
    ['amerihome',           'https://www.amerihomemortgage.com/'],
    ['phh mortgage',        'https://www.phhloans.com/'],
    ['flagstar',            'https://www.flagstar.com/'],
    ['united wholesale',    'https://www.uwm.com/'],
    ['better mortgage',     'https://www.better.com/'],
    ['lakeview loan',       'https://www.lakeviewloanservicing.com/'],
    ['cenlar',              'https://www.cenlar.com/'],
    ['servicemac',          'https://www.servicemac.com/'],

    // ── Fintech lenders & neobanks ────────────────────────────────────────────
    ['ally',                'https://www.ally.com/'],
    ['sofi',                'https://www.sofi.com/'],
    ['upgrade',             'https://www.upgrade.com/'],
    ['upstart',             'https://www.upstart.com/'],
    ['lendingclub',         'https://www.lendingclub.com/'],
    ['lending club',        'https://www.lendingclub.com/'],
    ['prosper',             'https://www.prosper.com/'],
    ['best egg',            'https://www.bestegg.com/'],
    ['avant',               'https://www.avant.com/'],
    ['lightstream',         'https://www.lightstream.com/'],
    ['happy money',         'https://www.happymoney.com/'],
    ['oportun',             'https://www.oportun.com/'],
    ['self financial',      'https://www.self.inc/'],
    ['self inc',            'https://www.self.inc/'],
    ['petal',               'https://www.petalcard.com/'],
    ['chime',               'https://www.chime.com/'],
    ['varo',                'https://www.varomoney.com/'],
    ['moneylion',           'https://www.moneylion.com/'],
    ['dave',                'https://dave.com/'],
    ['current',             'https://current.com/'],
    ['one finance',         'https://www.onefinance.com/'],
    ['marcus',              'https://www.marcus.com/'],
    ['goldman sachs',       'https://www.marcus.com/'],
    ['apple card',          'https://wallet.apple.com/'],
    ['paypal',              'https://www.paypal.com/myaccount/summary'],
    ['venmo',               'https://account.venmo.com/'],
    ['affirm',              'https://www.affirm.com/account'],
    ['klarna',              'https://app.klarna.com/'],
    ['afterpay',            'https://www.afterpay.com/'],
    ['zip',                 'https://account.zip.co/'],
    ['sezzle',              'https://dashboard.sezzle.com/'],

    // ── Store card networks ───────────────────────────────────────────────────
    ['synchrony',           'https://www.mysynchrony.com/'],
    ['comenity',            'https://d.comenity.net/'],
    ['bread financial',     'https://d.comenity.net/'],
    ['webbank',             'https://www.webbank.com/'],
    ['celtic bank',         'https://www.celticbank.com/'],
    ['target',              'https://www.target.com/redcard/manage'],
    ['barclays',            'https://www.barclaysus.com/all-products/credit-cards/make-payment.html'],
]

export function getPaymentUrl(institutionName: string): string | null {
    const normalized = institutionName.toLowerCase()
    for (const [key, url] of PAYMENT_URLS) {
        if (normalized.includes(key)) return url
    }
    return null
}
